# Generated by Django 5.1.4 on 2024-12-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batch',
            field=models.CharField(choices=[("bsse'01'", "BSSE'01'"), ("bsse'02'", "BSSE'02'"), ("bsse'03'", "BSSE'03'"), ("bsse'04'", "BSSE'04'"), ("bsse'05'", "BSSE'05'"), ("bsse'06'", "BSSE'06'"), ("bsse'07'", "BSSE'07'"), ("bsse'08'", "BSSE'08'"), ("bsse'09'", "BSSE'09'"), ("bsse'10'", "BSSE'10'"), ("bsse'11'", "BSSE'11'"), ("bsse'12'", "BSSE'12'"), ("bsse'13'", "BSSE'13'"), ("bsse'14'", "BSSE'14'"), ("bsse'15'", "BSSE'15'"), ("bsse'16'", "BSSE'16'")], max_length=50, null=True, verbose_name='Batch'),
        ),
    ]
