# Generated by Django 5.1.4 on 2024-12-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamregistration',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Payment not made yet'), ('pending', 'Payment being verified'), ('declined', 'Transaction Id did not match'), ('completed', 'Payment is succesfull')], default='unpaid', max_length=50),
        ),
    ]
