# Generated by Django 5.1.4 on 2024-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_teamregistration_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamregistration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='status',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
