# Generated by Django 5.1.4 on 2024-12-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_teamregistration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistration',
            name='trasaction_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Transaction Id'),
        ),
    ]
