# Generated by Django 5.1.4 on 2024-12-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_teamregistration_trasaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamregistration',
            options={'verbose_name': 'TeamRegistration', 'verbose_name_plural': 'TeamRegistrations'},
        ),
    ]
