# Generated by Django 5.1.4 on 2024-12-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_rename_trasaction_id_teamregistration_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction Id'),
        ),
    ]
