# Generated by Django 5.1.4 on 2024-12-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_teamregistration_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Payment being verified.'), ('declined', 'Transaction Id did not match.'), ('accepted', 'Payment is succesfull.')], default='pending', max_length=50),
        ),
    ]
