# Generated by Django 5.1.4 on 2024-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_team',
            field=models.IntegerField(default=10),
        ),
    ]
