# Generated by Django 5.1.4 on 2024-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_total_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='entry_fee',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(default=2),
        ),
    ]
