# Generated by Django 5.1.4 on 2024-12-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_entry_fee_game_player_count'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_count',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='userauth.player'),
        ),
    ]
