# Generated by Django 5.1.4 on 2024-12-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(default=2),
        ),
    ]
