# Generated by Django 5.1.4 on 2024-12-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_team_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_email',
            new_name='number',
        ),
    ]
