# Generated by Django 5.1.4 on 2024-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_rename_team_email_team_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment_method',
            field=models.CharField(default='offline', max_length=50),
        ),
    ]
